FROM openjdk:8-jdk

# Add backports
RUN echo "deb http://http.debian.net/debian jessie-backports main" >> /etc/apt/sources.list

# Upgrade and Install packages
RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends git openssh-server bsdtar maven libltdl7
RUN export tar='bsdtar'
# Prepare container for ssh
RUN mkdir /var/run/sshd && adduser --quiet jenkins && echo "jenkins:jenkins" | chpasswd

COPY docker /usr/bin/docker
COPY helm /usr/bin/helm
COPY slave.jar /usr/share/jenkins/slave.jar
COPY --chown=jenkins:jenkins kube-config /home/jenkins/.kube/config
COPY jenkins-slave /usr/bin/jenkins-slave

RUN chmod 775 /usr/bin/jenkins-slave
RUN groupadd -g 993 docker && usermod -a -G docker jenkins

ENV CI=true

ENTRYPOINT ["/usr/bin/jenkins-slave"]

